% Cover the checkerboard in an image.
function Iv_rm = remove_checkerboard(Iv, checkerboard_points, board_size)
    [topleft, botleft, botright, topright] = ...
        checkerboard_corners(checkerboard_points, board_size);
    mean_intensity = mean(Iv(:));
    Iv_rm = insertShape(Iv, ...
        'FilledPolygon', [topleft(1) topleft(2) ...
                          botleft(1) botleft(2) ...
                          botright(1) botright(2) ...
                          topright(1) topright(2)], ...
        'Color', [mean_intensity mean_intensity mean_intensity], ...
        'Opacity', 1);
    Iv_rm = Iv_rm(:, :, 3);
end
